[profile.default]
solc = "0.8.23"
evm_version = "paris"

libs = [ "../lib" ]

src = "src"
out = "out"
test = "../test/quark-proxy"

# optimizer config
optimizer = true
optimizer_runs = 1
bytecode_hash = "none"

[profile.ir]
via_ir = true
extra_output = [ "ir" ]
extra_output_files = [ "ir" ]
