name: lint

on:
  workflow_dispatch:
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies
        run: forge install

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge Format
        run: |
          forge fmt --check
        id: format

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: 19
      
      - name: Install dependencies
        run: yarn install --non-interactive --frozen-lockfile

      - name: Vendoza Audit
        run: yarn vendoza-audit  
